version: '3.5'

services:
  product_calc_postgres:
    container_name: product_calc_postgres
    image: postgres:14
    environment:
      POSTGRES_USER: product_calc
      POSTGRES_PASSWORD: product_calc
      PGDATA: /data/postgres
    volumes:
       - postgres:/var/www/product_calc/docker-volumes/postgres
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - product_calc
    restart: unless-stopped

  product_calc_pgadmin:
    container_name: product_calc_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: petr.ku@outlook.com
      PGADMIN_DEFAULT_PASSWORD: product_calc
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/www/product_calc/docker-volumes/pgadmin
    ports:
      - 127.0.0.1:5050:80
    networks:
      - product_calc
    restart: unless-stopped

networks:
  product_calc:
    driver: bridge

volumes:
  postgres:
  pgadmin:
